"""empty message

Revision ID: 3f76cdeb986d
Revises: 9eac0f3d7b1e
Create Date: 2023-04-20 22:08:38.234314

"""

# revision identifiers, used by Alembic.
revision = '3f76cdeb986d'
down_revision = '9eac0f3d7b1e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location')
    op.drop_table('product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('location_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('address', sa.VARCHAR(length=254), nullable=True),
    sa.Column('website', sa.VARCHAR(length=120), nullable=True),
    sa.Column('telephone', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
