"""Add extra message

Revision ID: 4e94c0b08ed
Revises: 42709384216
Create Date: 2015-06-24 21:42:41.466973

"""

# revision identifiers, used by Alembic.
revision = '4e94c0b08ed'
down_revision = '42709384216'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_item', sa.Column('extra', sa.String(length=254), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_item', 'extra')
    ### end Alembic commands ###
