"""Add user associations

Revision ID: 5c8378aa4dff
Revises: 55013fe95bea
Create Date: 2022-05-20 21:32:47.786340

"""

# revision identifiers, used by Alembic.
revision = '5c8378aa4dff'
down_revision = '55013fe95bea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('association', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('associations', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'associations')
    op.drop_column('order', 'association')
    # ### end Alembic commands ###
