"""empty message

Revision ID: 89b2c980b663
Revises: None
Create Date: 2024-07-24 14:58:50.071396

"""

# revision identifiers, used by Alembic.
revision = '89b2c980b663'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('courier_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.String(length=64), nullable=True),
    sa.Column('location_name', sa.String(length=128), nullable=True),
    sa.Column('starttime', sa.DateTime(), nullable=True),
    sa.Column('stoptime', sa.DateTime(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('slug', sa.String(length=8), nullable=True),
    sa.Column('association', sa.String(length=120), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('bias', sa.Integer(), nullable=True),
    sa.Column('microsoft_uuid', sa.String(length=120), nullable=True),
    sa.Column('associations', sa.String(length=255), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('microsoft_uuid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=120), nullable=True),
    sa.Column('dish_id', sa.String(length=64), nullable=True),
    sa.Column('dish_name', sa.String(length=120), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('price_modified', sa.DateTime(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('hlds_data_version', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_item_choice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('choice_id', sa.String(length=64), nullable=True),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=1), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('value', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_item_choice')
    op.drop_table('order_item')
    op.drop_table('user')
    op.drop_table('order')
    # ### end Alembic commands ###
