"""empty message

Revision ID: d27ed743a38a
Revises: 150252c1cdb1
Create Date: 2019-08-31 15:42:35.729563

"""

# revision identifiers, used by Alembic.
revision = 'd27ed743a38a'
down_revision = '150252c1cdb1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('selection_type', sa.Enum('single_select', 'multi_select', name='selectiontype'), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attribute_values',
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('price_addition', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attribute.id'], ),
    sa.PrimaryKeyConstraint('attribute_id')
    )
    op.create_table('product_attribute_association_table',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('attribute_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attribute_id'], ['attribute.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], )
    )
    op.add_column('product', sa.Column('comment', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###

    op.alter_column('product', 'price', existing_type=sa.Integer ,new_column_name='base_price')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('product', 'comment')
    op.drop_column('product', 'base_price')
    op.drop_table('product_attribute_association_table')
    op.drop_table('attribute_values')
    op.drop_table('attribute')
    # ### end Alembic commands ###
