"""Removed foreign key constraint

Revision ID: 42709384216
Revises: 57a00d0b7bc
Create Date: 2015-06-04 22:34:05.237943

"""

# revision identifiers, used by Alembic.
revision = '42709384216'
down_revision = '57a00d0b7bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_ibfk_1', 'order', type_='foreignkey')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('order_ibfk_1', 'order', 'user', ['courrier_id'], ['id'])
    ### end Alembic commands ###
